### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by TurboProgramming** [RiccardoBusetti/Colombo#19]
Can we edit the source code and publish the edited version again? By changing the name. We can credit. Is that possible?

**Comment by RiccardoBusetti** [comment]
Can you tell me what do you want to improve or change?

**Comment by TurboProgramming** [comment]
Not actually what I mean. I'm a mobile developer and want to change the software a lot from the base and republish it. I'm sure that you'll not want this for your own application. There are a lot changes to do. Please can I? I can credit the original program as I've said.

**Comment by TurboProgramming** [comment]
Not actually what I mean. I'm a mobile developer and want to change the software a lot from the base and republish it. I'm sure that you'll not want this for your own application. There are a lot changes to do. Please can I? I can credit the original program as I've said.

**Comment by RiccardoBusetti** [comment]
And you will use what of my app if you will recode it? The engine is the webview

**Comment by TurboProgramming** [comment]
No, I understood that part. Just the pre-designed UI. I just need to edit like a brand new application.

**Comment by RiccardoBusetti** [comment]
Yeah ok, and why taking my app if you want to redit it? Tell me which classes you want

**Comment by TurboProgramming** [comment]
Thanks for the permission. I'm actually a beginner I mean not too beginner but still started 1 year ago and I don't have much information so I needed a template and I was searching and found this. Also, your browser is a nice browser. Congratulations on the work.

**Comment by TurboProgramming** [comment]
I'll be also notifieing you from your email. What is your email address so we can get in touch easily?

**Comment by RiccardoBusetti** [comment]
My email is riccardob36@gmail.com, when you publish the app tell me and insert the name of creator

**Comment by RiccardoBusetti** [comment]
If you will steal my work prepare for a bad situation :)

**Comment by RiccardoBusetti** [comment]
But i know you will not so good luck :)

**Comment by TurboProgramming** [comment]
Thanks, check your email address that you've provided to me for further details.

**Comment by TurboProgramming** [comment]
Thanks, check your email address that you've provided to me for further details.
